sudo: required
services:
  - docker

before_install:
  - docker build -t dockeraws -f Dockerfile.dev .

script:
  - docker run -e CI=true dockeraws npm run test

deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESS_KEY_ID
  secret_access_key:
    secure: "$SECRET_ACCESS_KEY"
  region: "ap-south-1"
  app: "dockeraws"
  env: "Dockeraws-env"
  bucket_name: "elasticbeanstalk-ap-south-1-909952531829"
  bucket_path: "dockeraws"
  on:
    branch: master
